# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadGitHubNugetPackage@1
  inputs:
    packageName: 'githubNugetpackage'
    version: '2'

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'rangu9606'
    repositoryName: '$(Build.Repository.githubNugetpackage)'
    id: 'https://github.com/rangu9606/testing.git'